#!/bin/sh
cd ../conf
git pull >> update-log 2>&1
echo '<include file="'$1'.conf">'
rev=`git rev-parse HEAD`
echo '<alias text="CONFREV" replace="NOTICE $nick :Configuration rev ID is '$rev' for '$1'" operonly="yes">'
